### PR TITLE
A few improvements

### PR DESCRIPTION
**Pull request by ffeppon**
Dear Hugo,

Here are the changes I am proposing : 
- support for eps format in figure (use epstopdf and then use svg reader)
- allow the user to specify the figure height with the unit conventions
- allow the user to use blank text of given width in order to add space (similar to \vspace in latex). I don't know if this is the best usage but I noticed I got an error with text('',height=0.2) with the previous implementation. 
- fix a bug (not sure this was a bug?) with y-positioning. Before, doing text('Test',y=0.5) was not placing the text at the middle of the slide.
- Fix a bug with setting the width in percentage. At the percentage conversion a number<1 was divided by 100, which I think is a mistake, but I might be wrong.

Thanks any way for this library. This is the first thing a bit serious I find to write HTML5 slides without knowing anything from HTML5, but only a bit of beamer knowledge. I find that the writing of the library is rather well-organized and well-understood. I was able to understand and implement these changes after a few hours discovering the package. I might contribute if I need extra things. A thing which also would be nice would be letting the user the possibility to have graphics (images, videos) to be included through relative links and not in a gigantic html. Because the browser might take time to load all the videos at once.

Best
Florian

### CODE REVIEW

**Comment by hchauvet** [comment]
Thanks, 

I will check why checks failed asap and merge things.

Some quick answers:
- **allow the user to use blank text of given width in order to add space (similar to \vspace in latex). I don't know if this is the best usage but I noticed I got an error with text('',height=0.2) with the previous implementation.**
The way I add more space, is to set the position of the next element relative to the previous one (you could find some info in the doc here):
https://hchauvet.github.io/beampy/auto_tutorials/positioning_system.html#sphx-glr-auto-tutorials-positioning-system-py

But have a way to manage the spacing in "auto" mode could be a great thing, if the empty text does the trick for the moment it's great, but I will think of adding a "spacer" element. 

I'm also planning to introduce the same kind of box model like the one of css (with padding, margin and border)

- **fix a bug (not sure this was a bug?) with y-positioning. Before, doing text('Test',y=0.5) was not placing the text at the middle of the slide.**
It was not a bug, but rather an historical thing as we start with all sizes relative to the width of the presentation. But it was planned to move to the "height" of the slide for y position given in percentage. So I will merge your change and add a warning for old présentation if they want to revert to the old way with:
`DEFAULT_Y['unit']` = `'width'` at the beginning of their presentation.

 - **Fix a bug with setting the width in percentage. At the percentage conversion a number<1 was divided by 100, which I think is a mistake, but I might be wrong.**
Woh I didn't notice that, this seems correct, thx!

**Review by hchauvet — CHANGES_REQUESTED** [review]
Hi Florian,

To make tests pass could you change the way you check if width or height are given to a figure from (on line 263 of figure.py):
```python
            if 'width' in self.args and not 'height' in self.args:
                # SCALE OK need to keep the original viewBox !!!
                scale_x = (self.positionner.width/float(svgwidth)).value
                figure_height = float(svgheight) * scale_x
                figure_width = self.positionner.width.value
                # Add the correct first line and last
                tmphead = '\n<g transform="scale(%0.5f)">' % (scale_x)
            elif 'height' in self.args and not 'width' in self.args:
                figure_height = self.positionner.height.value
                scale_y = (self.positionner.height/float(svgheight)).value
                figure_width = float(svgwidth) * scale_y
                tmphead = '\n<g transform="scale(%0.5f)">' % (scale_y)

            output = tmphead + tmpfig + '</g>\n'
```

to something that check if width or height is None like
```python
            # Scale the figure according to the given width
            if self.width.value is not None and self.height.value is None:
                # SCALE OK need to keep the original viewBox !!!
                scale = (self.positionner.width/float(svgwidth)).value
                figure_height = float(svgheight) * scale
                figure_width = self.positionner.width.value

            # Scale the figure according to the given height
            if self.height.value is not None and self.width.value is None:
                figure_height = self.positionner.height.value
                scale = (self.positionner.height/float(svgheight)).value
                figure_width = float(svgwidth) * scale

            # Dont scale the figure let the user fix the width height
            if self.height.value is not None and self.width.value is not None:
                output = tmpfig
                figure_height = self.positionner.height.value
                figure_width = self.positionner.width.value
            else:
                # Apply the scaling to the figure
                tmphead = '\n<g transform="scale(%0.5f)">' % (scale)
                output = tmphead + tmpfig + '</g>\n'

```

And do the same for lines 310 to 317:
```python
            # Scale the figure according to the given width
            if self.width.value is not None and self.height.value is None:
                # SCALE OK need to keep the original viewBox !!!
                scale = (self.positionner.width/float(tmpwidth)).value
                figure_height = float(tmpheight) * scale
                figure_width = self.positionner.width.value

            # Scale the figure according to the given height
            if self.height.value is not None and self.width.value is None:
                figure_height = self.positionner.height.value
                scale = (self.positionner.height/float(tmpheight)).value
                figure_width = float(tmpwidth) * scale

            # Dont scale the figure let the user fix the width height
            if self.height.value is not None and self.width.value is not None:
                figure_height = self.positionner.height.value
                figure_width = self.positionner.width.value
```

Could you update your branch, so that it will update the PR and re-run the tests.
Best.

Hugo.

**Comment by ffeppon** [comment]
Dear Hugo

Your correction does not work because self.width.value is set by default to the document width at lines 155-156 
`python

            if self.width is None:
                self.width = document._slides[gcs()].curwidth
`
That is why I was relying on "self.args" instead of self.width.
Maybe this part requires a bit of cleaning then ? 

Thanks

**Comment by hchauvet** [comment]
Ok, maybe we could say that:

When no height and no width are given take the current width for this image (which is the width of the current group where your adding your image), so when **self.width** and **self.height** are None. 

We could change lines 155 - 156 to:
```python
if self.width is None and self.height is None:
    self.width = document._slides[gcs()].curwidth
```

Then on the **render** method keep testing on self.width.value and self.height.value (the .value comes from the register method which re-assign the self.width and self.height variables to a Length object via the the **update_size** method, not very clever but I will change that in the future to make things a bit less confusing).

Does it works on your side with those changes ?

**Comment by hchauvet** [comment]
We should also change around line **345**
```python
else:
   out_img = resize_raster_image(tmp_img, max_width=self.positionner.width.value)
```
to
```python
else:
   out_img = resize_raster_image(tmp_img, max_width=figure_width)
```

Best.
Hugo.

**Pull request closed without merging**
